# Etapa 1: build
FROM node:18 AS builder

WORKDIR /app

COPY . .

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install
RUN pnpm run build

# Etapa 2: producción 
FROM nginx:alpine

# Copia el build al directorio de nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copia un archivo de configuración personalizado de nginx si lo necesitas
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
